### PR TITLE
Feature/change chart.view api

### PR DESCRIPTION
**Pull request by klawr**
Implemented API changes as suggested.

Commit message is as follows:
```
Previously the chart was called by providing a xaxis and a yaxis
property. To better fit to other view methods this is changed to
use "show" and "of" to determine the element to represent on the chart.

One consequence of this change is, that the yaxis can represent only
one element (and not multiple by providing an array).

The xaxis is determined by a ref property (which does not differ much)
from the previously used xaxis property.
The naming of this property is a matter of future discussions.

The previously used ref property is therefore no longer used to
determine the referenced drive to get the nod on the chart for preview.
This drive is now automatically identified by
model.inputControlDrives[0].
One limitation is that this only works reliable if only one drive is
used as input (but this limitation is not new...)

If the ref property is not provided, the timer of the model is used.

Other changes are made to make the code more readable.
```

Please review for necessary treatment before merging.

### CODE REVIEW

**Comment by jauhl** [comment]
I’m not sure if I fully understand what you are proposing… Could you please provide following view (taken from mecEdit example crank-rocker) in the new syntax?
```json
{ "as":"chart","canvas":"chart1","x":40,"y":40,"b":200,"h":150,"t0":0.1,"Dt":3,"mode":"preview","ref":"a",
  "xaxis":{ "show":"w","of":"a" },
  "yaxis":{ "show":"w","of":"c" }
}
```

**Comment by klawr** [comment]
Sorry for the late answer.

The change is essentially in the definition of the `y-axis`. This is to align the syntax with other views.
In this case the only changes are in `x-axis` and `y-axis` being replaced with a `ref` and `show`, `of` respectively. If there is no `ref` given, it defaults to the `timer` of the model.
```
{ "as":"chart","canvas":"chart1","x":40,"y":40,"b":200,"h":150,"t0":0.1,"Dt":3,"mode":"preview","ref":"a",
  "ref":{ "show":"w","of":"a" }
  "show":"w","of":"c",
}
```

**Comment by goessner** [comment]
It should basically look like 

```json
{ "show":"wt","of":"c","as":"chart"}
```
conforming to all other views. The default x-axis values are corresponding time values. For other x-axis values I propose

```json
{ "show":"wt","of":"c","against":{"val": "w","of":"a"},"as":"chart" }
```
All additional members can follow. An existing "canvas" member is violating the 'ui' and 'graphics' agnosticism of 'mec2' and is not allowed. The controlling app has to decide, which canvas context to hand over to the view `draw` method. Using a chart web component this problem should go away by itself.

**Review by jauhl — APPROVED** [review]
While I agree that consistency among the api-methods is important it’s a bit of a bummer that features like multiple y-values are being omitted. But I guess that’s unavoidable when you try to simplify things.

The code looks fine as far as I can tell.

I’m also ok with either of the property-names `ref` or `against`.

The `canvas` member however is currently necessary to stop rendering charts on the main canvas when the environment provides additional canvas elements for charts. This could of course also become a flag in the show-object instead. The only place where this has to be changed is at https://github.com/goessner/mec2/blob/6f0a6560f02556276efefd17f427b23f3cf10abd/src/mec.model.js#L841

**Pull request merged**
